### PR TITLE
Fix TwoWayContactSyncAdapter

### PR DESCRIPTION
**Pull request by chriadam**

### CODE REVIEW

**Comment by matthewvogt** [comment]
It would be better to add a macro to conditionally output all those trace lines, rather than sprinkle #ifdef everywhere.

**Comment by chriadam** [comment]
Good point, will do.

**Comment by chriadam** [comment]
Fixed - the logging is now runtime-enabled via env var rather than #ifdef.

**Comment by matthewvogt** [comment]
LGTM

**Pull request merged**
